sudo: required
dist: trusty
language: cpp
compiler:
  - gcc
  - clang

env:
  matrix:
    - META_MAKE="cmake"
    - META_MAKE="qmake"
    - META_MAKE="qmake-qt4"

install: # Use this to install any prerequisites or dependencies necessary to run the build
  - sudo apt-get -qq install qt5-default libqt4-dev qt4-qmake

script: # build
  - mkdir build; cd build
  - if [ "$META_MAKE" != "qmake-qt4" ] ; then $META_MAKE .. ; fi
  - if [ "$META_MAKE" != "qmake-qt4" ] ; then make -j$(nproc) ; fi
  - |
    if [ "$META_MAKE" == "qmake-qt4" ] ; then
      qmake .. CONFIG+=release PREFIX=/usr
      make -j$(nproc)
      make INSTALL_ROOT=appdir -j$(nproc) install ; find appdir/
      wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
      chmod a+x linuxdeployqt-continuous-x86_64.AppImage
      unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
      export VERSION=$(git rev-parse --short HEAD) # linuxdeployqt uses this for naming the file
      ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage
      find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
      # curl --upload-file APPNAME*.AppImage https://transfer.sh/APPNAME-git.$(git rev-parse --short HEAD)-x86_64.AppImage
      wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
      bash upload.sh APPNAME*.AppImage*
    fi

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
